[
  {
    id: '333171',
    person: { firstName: 'HUGH', lastName: 'ALBRITTON' },
    firmRelationships: [
      {
        id: '903943',
        name: 'AlternateInfoReq',
        filterFlag: false,
        description: 'Alternate Information Required',
        firmRelationshipId: '5',
        value: 'Y',
        typeCode: null,
      },
      {
        id: '903940',
        name: 'WorksForFirm',
        filterFlag: true,
        description: 'Works for Firm',
        firmRelationshipId: '2',
        value: 'N',
        typeCode: null,
      },
      {
        id: '903941',
        name: 'RegisteredRep',
        filterFlag: true,
        description: 'Registered Representative',
        firmRelationshipId: '3',
        value: 'N',
        typeCode: null,
      },
      {
        id: '903942',
        name: 'RegisteredPrincipal',
        filterFlag: true,
        description: 'Registered Principal',
        firmRelationshipId: '4',
        value: 'N',
        typeCode: null,
      },
    ],
    roleContacts: [
      {
        assignedTimestamp: '2010-01-26T16:24:26.000Z',
        role: {
          id: '32',
          name: 'CRD Renewals',
          required: false,
          annualReport: false,
          description: 'CRD Renewals',
          firmRelationships: [],
        },
        contactInfo: { addresses: [{ label: 'Primary', address: { city: 'ALPHARETTA' } }] },
      },
      {
        assignedTimestamp: '2010-01-26T16:24:19.000Z',
        role: {
          id: '27',
          name: 'Regulatory Inquiries',
          required: true,
          annualReport: false,
          description: 'Regulatory Inquiries',
          firmRelationships: [],
        },
        contactInfo: { addresses: [{ label: 'Primary', address: { city: 'ALPHARETTA' } }] },
      },
      {
        assignedTimestamp: '2002-12-04T17:42:00.000Z',
        role: {
          id: '1',
          name: 'Chief Executive Officer (CEO) or Partner',
          required: true,
          annualReport: false,
          description: 'Chief Executive Officer (CEO) or Partner',
          firmRelationships: [
            { firmRelationshipId: '4', id: '2', name: 'RegisteredPrincipal' },
            { firmRelationshipId: '2', id: '8', name: 'WorksForFirm' },
          ],
        },
        contactInfo: { addresses: [{ label: 'Primary', address: { city: 'ALPHARETTA' } }] },
      },
      {
        assignedTimestamp: '2002-12-04T17:42:00.000Z',
        role: {
          id: '2',
          name: 'Executive Representative (ER)',
          required: true,
          annualReport: true,
          description: 'Executive Representative (ER)',
          firmRelationships: [
            { firmRelationshipId: '2', id: '9', name: 'WorksForFirm' },
            { firmRelationshipId: '4', id: '6', name: 'RegisteredPrincipal' },
          ],
        },
        contactInfo: { addresses: [{ label: 'Primary', address: { city: 'ALPHARETTA' } }] },
      },
      {
        assignedTimestamp: '2002-12-05T12:40:00.000Z',
        role: {
          id: '4',
          name: 'Anti-Money Laundering Compliance Contact(AML)-Primary',
          required: true,
          annualReport: true,
          description: 'Anti-Money Laundering Compliance Contact(AML) - Primary ',
          firmRelationships: [],
        },
        contactInfo: { addresses: [{ label: 'Primary', address: { city: 'ALPHARETTA' } }] },
      },
      {
        assignedTimestamp: '2002-12-05T12:40:00.000Z',
        role: {
          id: '5',
          name: 'Chief Financial Officer',
          required: false,
          annualReport: false,
          description: 'Chief Financial Officer',
          firmRelationships: [
            { firmRelationshipId: '4', id: '7', name: 'RegisteredPrincipal' },
            { firmRelationshipId: '2', id: '12', name: 'WorksForFirm' },
          ],
        },
        contactInfo: { addresses: [{ label: 'Primary', address: { city: 'ALPHARETTA' } }] },
      },
      {
        assignedTimestamp: '2004-07-20T14:08:26.000Z',
        role: {
          id: '7',
          name: 'Chief Technology Officer',
          required: false,
          annualReport: false,
          description: 'Chief Technology Officer',
          firmRelationships: [],
        },
        contactInfo: { addresses: [{ label: 'Primary', address: { city: 'ALPHARETTA' } }] },
      },
      {
        assignedTimestamp: '2002-12-05T12:40:00.000Z',
        role: {
          id: '10',
          name: 'Chief Compliance Officer',
          required: true,
          annualReport: false,
          description: 'Chief Compliance Officer',
          firmRelationships: [
            { firmRelationshipId: '4', id: '1', name: 'RegisteredPrincipal' },
            { firmRelationshipId: '2', id: '10', name: 'WorksForFirm' },
          ],
        },
        contactInfo: { addresses: [{ label: 'Primary', address: { city: 'ALPHARETTA' } }] },
      },
      {
        assignedTimestamp: '2004-07-20T14:11:32.000Z',
        role: {
          id: '20',
          name: 'Emergency Contact (BCP) - Primary',
          required: true,
          annualReport: true,
          description: 'Emergency Contact (BCP) - Primary',
          firmRelationships: [
            { firmRelationshipId: '5', id: '4', name: 'AlternateInfoReq' },
            { firmRelationshipId: '2', id: '11', name: 'WorksForFirm' },
            { firmRelationshipId: '4', id: '3', name: 'RegisteredPrincipal' },
          ],
        },
        contactInfo: { addresses: [{ label: 'Primary', address: { city: 'ALPHARETTA' } }] },
      },
      {
        assignedTimestamp: '2004-07-20T14:19:16.000Z',
        role: {
          id: '21',
          name: 'Continuing Education',
          required: true,
          annualReport: true,
          description: 'Continuing Education',
          firmRelationships: [],
        },
        contactInfo: { addresses: [{ label: 'Primary', address: { city: 'ALPHARETTA' } }] },
      },
    ],
    contactInfo: {
      addresses: [{ label: 'Primary', address: { city: 'ALPHARETTA' } }],
      emails: [
        { emailAddress: 'AMSECGA@AOL.COM', label: 'Primary', primary: true },
        { emailAddress: 'noemail@aol.com', label: 'Secondary', primary: false },
      ],
    },
  },
  {
    id: '331162',
    person: { firstName: 'CATHY', lastName: 'HANSEN' },
    firmRelationships: [
      {
        id: '896698',
        name: 'RegisteredRep',
        filterFlag: true,
        description: 'Registered Representative',
        firmRelationshipId: '3',
        value: 'N',
        typeCode: null,
      },
      {
        id: '896699',
        name: 'RegisteredPrincipal',
        filterFlag: true,
        description: 'Registered Principal',
        firmRelationshipId: '4',
        value: 'N',
        typeCode: null,
      },
      {
        id: '896700',
        name: 'AlternateInfoReq',
        filterFlag: false,
        description: 'Alternate Information Required',
        firmRelationshipId: '5',
        value: 'Y',
        typeCode: null,
      },
      {
        id: '896697',
        name: 'WorksForFirm',
        filterFlag: true,
        description: 'Works for Firm',
        firmRelationshipId: '2',
        value: 'N',
        typeCode: null,
      },
    ],
    roleContacts: [
      {
        assignedTimestamp: '2008-01-14T09:57:09.000Z',
        role: {
          id: '22',
          name: 'Regulatory Inquiries',
          required: true,
          annualReport: true,
          description: 'Regulatory Inquiries',
          firmRelationships: [{ firmRelationshipId: '5', id: '5', name: 'AlternateInfoReq' }],
        },
        contactInfo: { addresses: [{ label: 'Primary', address: { city: 'ALPHARETTA' } }] },
      },
    ],
    contactInfo: {
      addresses: [{ label: 'Primary', address: { city: 'ALPHARETTA' } }],
      emails: [
        { emailAddress: 'AMSecGA@aol.com', label: 'Primary', primary: true },
        { emailAddress: 'noemail@aol.com', label: 'Secondary', primary: false },
      ],
    },
  },
];
